### ISSUE TITLE
Moderator Permissions

### ISSUE THREAD

**Issue by mrix2000** [axew3/phpBB-image-attachments-rotation#3]
My Global Moderator tried to edit a members post which contains a image which was showing on its side to find once he rotated it and went to press the Save button it disallowed him and stated he never had permissions etc, I went to edit it myself and save and all was fine.

**Comment by mrix2000** [comment]
There also appear to be another issue with the Moderators as its causing them to keeping logging out, I have been required to disable the EXT for the time being which has stopped the issue.

**Comment by axew3** [comment]
Fixed all the above.
It will be necessary to substitute the file:
_ext/w3all/imageattachrotation/core/**fileRotate.php**_
into
_ext/w3all/imageattachrotation/**core**_
with the new one patched.
