### ISSUE TITLE
This EXT no longer works

### ISSUE THREAD

**Issue by mrix2000** [axew3/phpBB-image-attachments-rotation#5]
This EXT has stopped working with the latest phpbb software version update 3.3.13 
If you click the image to get the correct orientation and then click the post submit button the images revert back to their original image position, having a look through the discussion topic there is a couple of people posted with the same issue.

**Comment by axew3** [comment]
Should be all fixed at the date of this post

**Comment by axew3** [comment]
Should be all fixed at the date of this post

**Comment by axew3** [comment]
Should be all fixed at the date of this post

**Comment by axew3** [comment]
Please, re-download now the extensions files, all files have been updated and the release has been removed and re-published.
