### ISSUE TITLE
Moderator no permissions issue

### ISSUE THREAD

**Issue by mrix2000** [axew3/phpBB-image-attachments-rotation#7]
My moderator can no longer use the ext with this version as he gets a error pop up box showing "No Permissions" his screenshot is below.
.
![Untitled](https://github.com/user-attachments/assets/2bc55b55-600e-464b-acad-05e649447f36)

**Comment by axew3** [comment]
Hello! No, in fact moderators are NOT allowed anymore to manage attachments, only admins and attach owner.
Ok, going to fix this issue, it is required just an instruction on code.  The code will be patched about this,  i will return in reply here.

**Comment by axew3** [comment]
Fixed on 1.0.7 just released.
Please update the post at phpBB.com on the related topic, Thank  You!
